### ISSUE TITLE
Type error on streamingMode

### ISSUE THREAD

**Issue by oliverrees** [neurosity/neurosity-sdk-js#105]
Using the boilerplate code from the [bluetooth streaming tutorial](https://docs.neurosity.co/docs/api/bluetooth-web/) streaming mode returns a type error for any input (including the values that are meant to be typed: 'bluetooth-with-wifi-fallback' etc)

```
import { Neurosity, WebBluetoothTransport } from "@neurosity/sdk";
...
const neurosity = new Neurosity({
        autoSelectDevice: true,
        bluetoothTransport: new WebBluetoothTransport(),
        streamingMode: 'wifi-only'
      });
```

**Comment by alexcastillo** [comment]
Hey @oliverrees,

Thanks for reporting this issue.

I've published @neurosity/sdk@6.5.5 with an enum you can import when using TypeScript:

```ts
import { Neurosity, WebBluetoothTransport, STREAMING_MODE } from "@neurosity/sdk";

const neurosity = new Neurosity({
    autoSelectDevice: true,
    bluetoothTransport: new WebBluetoothTransport(),
    streamingMode: STREAMING_MODE.WIFI_ONLY
});
```
