### ISSUE TITLE
Multiple kinesis streams not working properly

### ISSUE THREAD

**Issue by juank-pa** [neurosity/neurosity-sdk-js#107]
I noticed that when subscribing to multiple kinesis streams e.g. rightArm and leftArm, one of them becomes receives any activity, while the other one is receiving more activity than normal, like if it was receiving activity for both streams at the same time. Nevertheless, this activity data is always marked as being a single label, so it is still imposible to determine where it is coming from.

Is this a known limitation of the system?

I also noticed all the neurosity system is implemented based on firebase DB actions. Is the firebase neurosity underlying architecture also open source? Can we learn somwhow how is that implemented to see if there is a way to overcome this issue?

Also, I noticed that this does not only happens using the SDK but also while listening to kinesis in the neurosity portal. So it must be a known limitation.

Thanks in advance

**Comment by juank-pa** [comment]
Also, I noticed that this does not only happens using the SDK but also while listening to kinesis in the neurosity portal. So it must be a known limitation.

**Comment by alexcastillo** [comment]
Hi @juank-pa,

Yes, this is a known limitation.

The Neurosity Console uses the SDK to train and read Kinesis data. We do use Firebase for cloud streaming. The SDK is open source as you can see, but unfortunately, our OS is not., We do recommend for folks to create their own models using the raw data from the SDK .

I hope this is helpful.

Best,
Alex
