### ISSUE TITLE
Long setTimeout. ReactNative Android complains

### ISSUE THREAD

**Issue by larskarbo** [neurosity/neurosity-sdk-js#54]
Getting this warning often when running `notion-js` on android:
![image](https://user-images.githubusercontent.com/10865165/89532326-ea869480-d7f1-11ea-8225-0f5549410508.png)

Don't know if it is some other way to do it in `notion-js` or if I should try to silence the warning.

**Comment by alexcastillo** [comment]
The long timer is important for our time synchronization strategy. I can't think of a way to silence this warning since it looks it is produced by Android.

**Comment by alexcastillo** [comment]
@larskarbo Are you initializing notion with timesync enabled?

```
new Notion({
  timesync: true
});
```
